sudo: enabled
os: linux
language: ruby
rvm:
  - 2.6.1

before_install:
  - gem update --system
  - gem install bundler
  - gem install rails

install: bundle install --jobs=3 --retry=3

script:
  - rails db:migrate RAILS_ENV=test
  - rails test